Repository KipData/kipdb, pull requests merged in 2023-07, with the labels that each got.

#28 Feat/table multiple implementations
  src/kernel/io/mem.rs
  src/kernel/io/mod.rs
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/iterator/level_iter.rs
  src/kernel/lsm/iterator/merging_iter.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/ss_table/loader.rs
  src/kernel/lsm/ss_table/mod.rs
  src/kernel/lsm/storage.rs
  src/kernel/lsm/table/loader.rs
  src/kernel/lsm/table/meta.rs
  src/kernel/lsm/table/mod.rs
  src/kernel/lsm/table/scope.rs
  src/kernel/lsm/table/skip_table/iter.rs
  src/kernel/lsm/table/skip_table/mod.rs
  src/kernel/lsm/table/ss_table/block.rs
  src/kernel/lsm/table/ss_table/block_iter.rs
  src/kernel/lsm/table/ss_table/footer.rs
  src/kernel/lsm/table/ss_table/iter.rs
  src/kernel/lsm/table/ss_table/mod.rs
  src/kernel/lsm/version/cleaner.rs
  src/kernel/lsm/version/edit.rs
  src/kernel/lsm/version/iter.rs
  src/kernel/lsm/version/mod.rs
  src/kernel/lsm/version/status.rs
  src/kernel/lsm/version/test.rs
  tests/tests.rs
Labels: enhancement

#35 Feat/seek compaction
  src/bench/kernel_bench.rs
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/iterator/full_iter.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/storage.rs
  src/kernel/lsm/table/loader.rs
  src/kernel/lsm/table/scope.rs
  src/kernel/lsm/table/skip_table/iter.rs
  src/kernel/lsm/table/skip_table/mod.rs
  src/kernel/lsm/table/ss_table/mod.rs
  src/kernel/lsm/version/edit.rs
  src/kernel/lsm/version/mod.rs
  src/kernel/lsm/version/status.rs
  src/kernel/sled_storage.rs
  src/lib.rs
  src/net/server.rs
  tests/tests.rs
Labels: bug, enhancement, invalid

#37 Fix/data overwriting
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/storage.rs
  src/kernel/lsm/table/loader.rs
  src/kernel/lsm/table/mod.rs
  src/kernel/lsm/table/scope.rs
  src/kernel/lsm/table/skip_table/iter.rs
  src/kernel/lsm/table/skip_table/mod.rs
  src/kernel/lsm/table/ss_table/block.rs
  src/kernel/lsm/table/ss_table/mod.rs
  src/kernel/lsm/version/mod.rs
  src/kernel/mod.rs
  src/net/server.rs
Labels: bug

#39 fix: `compactor_tx` wrong throwing `ChannelCloseError`
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/storage.rs
Labels: bug

#36 feat(version): impl Trait Display for Version
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/version/mod.rs
  src/kernel/lsm/version/status.rs
Labels: enhancement

#40 Docs/examples
  Cargo.toml
  README.md
  examples/mvcc.rs
  examples/scan_read.rs
  examples/simple_crud.rs
  src/bin/cli.rs
  src/kernel/lsm/iterator/merging_iter.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/storage.rs
  src/kernel/lsm/version/edit.rs
  src/kernel/utils/lru_cache.rs
Labels: documentation
