Repository KipData/kipdb, pull requests merged in 2023-06, with the labels that each got.

#6 Feat/range
  src/error.rs
  src/kernel/lsm/block.rs
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/iterator/block_iter.rs
  src/kernel/lsm/iterator/full_iter.rs
  src/kernel/lsm/iterator/level_iter.rs
  src/kernel/lsm/iterator/merging_iter.rs
  src/kernel/lsm/iterator/mod.rs
  src/kernel/lsm/iterator/ss_table_iter.rs
  src/kernel/lsm/iterator/version_iter.rs
  src/kernel/lsm/log.rs
  src/kernel/lsm/lsm_kv.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/ss_table.rs
  src/kernel/lsm/version.rs
  src/lib.rs
Labels: enhancement

#14 feat(trigger): 新增触发器，用于支持多种Minor Compaction的触发策略
  src/kernel/lsm/iterator/full_iter.rs
  src/kernel/lsm/lsm_kv.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/trigger.rs
Labels: enhancement

#16 fix(bench): 修复无界隧道导致内存溢出问题，同时避免benchmark创建新实例时导致上个实例未完整结束的问题
  README.md
  src/bench/kernel_bench.rs
  src/kernel/lsm/lsm_kv.rs
  src/kernel/lsm/mvcc.rs
Labels: bug

#17 ": add pr template
  .github/pull_request_template.md
Labels: documentation

#18 *: add issue temp
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#21 feat(mvcc): 事务支持Range查询
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/trigger.rs
  src/kernel/lsm/version.rs
Labels: enhancement

#23 fix(trigger): Add a reset method
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/trigger.rs
Labels: bug, invalid

#24 config: 提升发布版本
  Cargo.toml
  README.md
Labels: bug

#25 Level 0 memorization
  src/bench/kernel_bench.rs
  src/kernel/io/mem.rs
  src/kernel/lsm/compactor.rs
  src/kernel/lsm/iterator/full_iter.rs
  src/kernel/lsm/iterator/level_iter.rs
  src/kernel/lsm/iterator/merging_iter.rs
  src/kernel/lsm/iterator/mod.rs
  src/kernel/lsm/log.rs
  src/kernel/lsm/mem_table.rs
  src/kernel/lsm/mod.rs
  src/kernel/lsm/mvcc.rs
  src/kernel/lsm/ss_table/block.rs
  src/kernel/lsm/ss_table/block_iter.rs
  src/kernel/lsm/ss_table/footer.rs
  src/kernel/lsm/ss_table/iter.rs
  src/kernel/lsm/ss_table/loader.rs
  src/kernel/lsm/ss_table/meta.rs
  src/kernel/lsm/ss_table/mod.rs
  src/kernel/lsm/storage.rs
  src/kernel/lsm/version.rs
  src/kernel/lsm/version/cleaner.rs
  src/kernel/lsm/version/edit.rs
  src/kernel/lsm/version/iter.rs
  src/kernel/lsm/version/meta.rs
  src/kernel/lsm/version/mod.rs
  src/kernel/lsm/version/status.rs
  src/kernel/lsm/version/test.rs
  src/kernel/mod.rs
  src/kernel/sled_storage.rs
  src/net/server.rs
  tests/tests.rs
Labels: enhancement

#26 feat(ci): Add code review gpt bot.
  .cargo/config
  .github/workflows/ci.yml
  .github/workflows/cr.yml
Labels: enhancement
